name: pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: copy repositories from git
        uses: actions/checkout@v3.6.0

      - name: Python install
        uses: actions/setup-python@v4
        with:
          python-version: "^3.10"

